config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  namespace :admin do
    resources :rentals do
      post 'calculate-rental', to: 'rentals#calculate_rental_value', on: :new
    end
    resources :people
    resources :vehicles

    root to: 'rentals#index'
  end

  root to: 'home#index'
end

app/models/rental.rb
# frozen_string_literal: true

class Rental < ApplicationRecord
  belongs_to :person
  belongs_to :vehicle

  scope :in_progress, -> { where(return_date: nil) }
  scope :by_vehicle_type, (lambda do |type|
    joins(:vehicle).where('vehicles.vehicle_type = ?', type)
  end)
  scope :delayeds, -> { where('end_date < ?', Time.now).in_progress }

  validates_presence_of :person, :vehicle, :start_date, :end_date
  validate :person_already_renting?
  validate :person_can_rent?
  validate :start_and_end_date

  def person_already_renting?
    if person&.renting? &&
       person.rentals.in_progress.first != self
      errors.add(:person_id, :person_already_renting)
    end
  end

  def person_can_rent?
    unless person.can_rent?(vehicle.vehicle_type)
      errors.add(:person_id, :person_cant_rent)
      errors.add(:vehicle_id, :vehicle_cant_rent)
    end

    true
  end

  def start_and_end_date
    return false if end_date.nil? || start_date.nil?

    if end_date < start_date
      errors.add(:end_date, :end_date_less_than_start_date)
    else
      true
    end
  end

  def delayed?
    (end_date < Time.now) && return_date.nil?
  end
end

app/controllers/admin/rentals_controller.rb
# frozen_string_literal: true

class Admin
  class RentalsController < Admin::BaseController
    before_action :set_rental, only: %i[edit update show]
    before_action :set_people, :set_vehicles, except: :index

    def index
      @rentals = Rental.all.paginate(page: params[:page] || 1, per_page: 10)
    end

    def new
      @rental = Rental.new
    end

    def create
      @rental = Rental.create(rental_params)

      if @rental.save
        redirect_to admin_rentals_path, notice: 'Adicionado com sucesso!'
      else
        render :new
      end
    end

    def update
      if @rental.update(rental_params)
        redirect_to admin_rentals_path, notice: 'Salvo com sucesso!'
      else
        render :edit
      end
    end

    def show
      redirect_to edit_admin_rental_path(@rental)
    end

    def destroy
      @rental = Rental.find(params[:id])
      @rental.destroy
      redirect_to admin_rentals_path, notice: 'Removido com sucesso!'
    rescue ActiveRecord::RecordNotFound
      redirect_to admin_rentals_path, alert: 'Registro já foi removido'
    rescue ActiveRecord::RecordNotDestroyed
      redirect_to admin_rentals_path, alert: 'Não foi possível remover'
    end

    def calculate_rental_value
      vehicle = Vehicle.find calculate_params[:vehicle_id]
      end_date = calculate_params[:end_date].to_date
      start_date = calculate_params[:start_date].to_date
      days = (end_date - start_date).to_i
      value = vehicle.daily_rate * days
      render json: { value: value }
    end

    private

    def rental_params
      params.require(:rental).permit(
        :person_id,
        :vehicle_id,
        :value,
        :start_date,
        :end_date,
        :withdrawal_date,
        :return_date
      )
    end

    def calculate_params
      params.require(:rental).permit(
        :vehicle_id,
        :start_date,
        :end_date
      )
    end

    def set_rental
      @rental = Rental.find(params[:id])
    end

    def set_people
      @people = Person.all
    end

    def set_vehicles
      @vehicles = Vehicle.all
    end
  end
end

app/views/admin/rentals/_form.html.erb
<%= form_for [:admin, @rental] do |f| %>
  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @rental.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-row">
    <div class="form-group col-md-12">
      <%= f.label :person_id %>
      <%= f.select :person_id, @people.collect { |person| [person.full_name, person.id] }, { prompt: t('select') }, class: 'form-control' %>
    </div>

    <div class="form-group col-md-12">
      <%= f.label :vehicle_id %>
      <%= f.select :vehicle_id, @vehicles.collect { |vehicle| [vehicle.model, vehicle.id] }, { prompt: t('select') }, class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :start_date %>
      <%= f.date_field :start_date, class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :end_date %>
      <%= f.date_field :end_date, class: 'form-control' %>
    </div>

    <div class="form-group col-md-12">
      <%= f.label :value %>
      <div class="input-group">
        <div class="input-group-prepend">
          <div class="input-group-text">R$</div>
        </div>
        <%= f.number_field :value, value: @rental.value ? '%.2f' % @rental.value : nil, min: 0, step: :any, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :withdrawal_date %>
      <%= f.date_field :withdrawal_date, class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :return_date %>
      <%= f.date_field :return_date, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit t('save'), class: 'btn btn-primary' %>
  <%= link_to t('back'), :back, class: 'btn btn-secondary' %>
<% end %>

app/views/admin/rentals/edit.html.erb
<h2>Editar locação</h2>

<%= render 'form' %>

app/views/admin/rentals/index.html.erb
<h1 class="title">Locações</h1>

<div class="mb-3">
  <%= link_to 'Novo aluguel', new_admin_rental_path, class: 'btn btn-primary' %>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Veículo</th>
      <th scope="col">Pessoa</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @rentals.each do |rental| %>
    <tr>
      <td>
        <%= link_to rental.id, edit_admin_rental_path(rental) %>
      </td>
      <td>
        <%= link_to rental.vehicle.model, edit_admin_rental_path(rental) %>
      </td>
      <td>
        <%= rental.person&.full_name %>
      </td>
      <td>
        <%= link_to admin_rental_path(rental), class: 'btn btn-primary' do %>
          <i class="fa fa-eye"></i>
        <% end %>
        <%= link_to admin_rental_path(rental), method: :delete, class: 'btn btn-danger', data: { confirm: t(:are_you_sure)} do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @rentals, list_classes: %w(pagination justify-content-center), previous_label: '<<', next_label: '>>' %>

app/views/admin/rentals/new.html.erb
<h2>Nova locação</h2>

<%= render 'form' %>