config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  namespace :admin do
    resources :rentals do
      post 'calculate-rental', to: 'rentals#calculate_rental_value', on: :new
    end
    resources :people
    resources :vehicles

    root to: 'rentals#index'
  end

  root to: 'home#index'
end

app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  enum vehicle_type: {
    car: 'car',
    motorcycle: 'motorcycle',
    truck: 'truck',
    bus: 'bus',
    small_truck: 'small_truck'
  }

  scope :cant_rent_wednesdays, -> { where('license_plate LIKE ?', '%4') }
  scope :by_type, ->(type) { where(vehicle_type: type) }
end

app/controllers/admin/vehicles_controller.rb
# frozen_string_literal: true

class Admin
  class VehiclesController < Admin::BaseController
    before_action :set_vehicle, only: %i[edit update show]

    def index
      @vehicles = Vehicle.all.paginate(page: params[:page] || 1, per_page: 10)
    end

    def new
      @vehicle = Vehicle.new
    end

    def create
      @vehicle = Vehicle.create(vehicle_params)

      if @vehicle.save
        redirect_to admin_vehicles_path, notice: 'Adicionado com sucesso!'
      else
        render :new
      end
    end

    def update
      if @vehicle.update(vehicle_params)
        redirect_to admin_vehicles_path, notice: 'Salvo com sucesso!'
      else
        render :edit
      end
    end

    def destroy
      @vehicle = Vehicle.find(params[:id])
      @vehicle.destroy
      redirect_to admin_vehicles_path, notice: 'Removido com sucesso!'
    rescue ActiveRecord::RecordNotFound
      redirect_to admin_vehicles_path, alert: 'Registro já foi removido'
    rescue ActiveRecord::RecordNotDestroyed
      redirect_to admin_vehicles_path, alert: 'Não foi possível remover'
    end

    private

    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    def vehicle_params
      params.require(:vehicle).permit(
        :model,
        :year,
        :license_plate,
        :color,
        :vehicle_type
      )
    end
  end
end

app/views/admin/vehicles/_form.html.erb
<%= form_for [:admin, @vehicle] do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @vehicle.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :model %>
      <%= f.text_field :model, class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :license_plate %>
      <%= f.text_field :license_plate, class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :vehicle_type %>
      <%= f.select(:vehicle_type, Vehicle.vehicle_types.keys.map {|type| [Vehicle.human_attribute_name("vehicle_type.#{type}"), type]}, { prompt: t('select') }, class: 'form-control' ) %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :color %>
      <%= f.text_field :color, class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :year %>
      <%= f.text_field :year, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit t('save'), class: 'btn btn-primary' %>
  <%= link_to t('back'), :back, class: 'btn btn-secondary' %>
<% end %>

app/views/admin/vehicles/edit.html.erb
<h2>Editar veículo</h2>

<%= render 'form' %>

app/views/admin/vehicles/index.html.erb
<h1 class="title">Veículos</h1>

<div class="mb-3">
  <%= link_to 'Adicionar veículo', new_admin_vehicle_path, class: 'btn btn-primary' %>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Placa</th>
      <th scope="col">Modelo</th>
      <th scope="col">Tipo</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @vehicles.each do |vehicle| %>
    <tr>
      <td>
        <%= link_to vehicle.license_plate, edit_admin_vehicle_path(vehicle) %>
      </td>
      <td>
        <%= link_to vehicle.model, edit_admin_vehicle_path(vehicle) %>
      </td>
      <td>
        <%= Vehicle.human_attribute_name("vehicle_type.#{vehicle.vehicle_type}") %>
      </td>
      <td>
        <%= link_to edit_admin_vehicle_path(vehicle), class: 'btn btn-primary' do %>
          <i class="fa fa-eye"></i>
        <% end %>
        <%= link_to admin_vehicle_path(vehicle), method: :delete, class: 'btn btn-danger', data: { confirm: t(:are_you_sure)} do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @vehicles, list_classes: %w(pagination justify-content-center), previous_label: '<<', next_label: '>>' %>

app/views/admin/vehicles/new.html.erb
<h2>Adicionar veículo</h2>

<%= render 'form' %>