config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  namespace :admin do
    resources :rentals do
      post 'calculate-rental', to: 'rentals#calculate_rental_value', on: :new
    end
    resources :people
    resources :vehicles

    root to: 'rentals#index'
  end

  root to: 'home#index'
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  has_many :phones, dependent: :destroy
  has_many :rentals
  has_one :license
  validates :name, :document, presence: true

  accepts_nested_attributes_for :phones, allow_destroy: true

  delegate :modalities, to: :license, prefix: true

  scope :by_modality, (lambda do |modality|
    joins(:license).where('licenses.modalities = ?', modality)
  end)

  # rubocop:disable MethodLength, AbcSize, CyclomaticComplexity
  # disabled rubocop here because it's a switch case,
  # so it has is many lines and is complex
  # I could divide it on 2 methods, but it does not make sense for me
  def can_rent?(vehicle_type = '')
    can_rent = of_age? && !license.expired?
    case vehicle_type
    when 'motorcycle'
      can_rent && license.to_drive_motorcycle?
    when 'car'
      can_rent && license.to_drive_car?
    when 'small_truck'
      can_rent && license.to_drive_small_truck?
    when 'truck'
      can_rent_truck?
    when 'bus'
      can_rent_bus?
    else
      can_rent
    end
  end
  # rubocop:enable MethodLength, AbcSize, CyclomaticComplexity

  def can_rent_truck?
    !license.expired? && age >= 60 && license.to_drive_truck?
  end

  def can_rent_bus?
    !license.expired? && age >= 40 && license.to_drive_bus?
  end

  def of_age?
    return true if Date.today.year - birthdate.year > 21

    if Date.today.year - birthdate.year == 21 &&
       check_month_and_day
      return true
    end

    false
  end

  def check_month_and_day
    if Date.today.month > birthdate.month ||
       (Date.today.month == birthdate.month &&
       Date.today.day >= birthdate.day)
      return true
    end

    false
  end

  def renting?
    rentals.in_progress.present?
  end

  def age
    ((Time.zone.now - birthdate.to_time) / 1.year.seconds).floor
  end

  def full_name
    "#{name} #{surname}".squish
  end

  def total_rentals_value
    rentals.sum(:value)
  end
end

app/controllers/admin/people_controller.rb
# frozen_string_literal: true

class Admin
  class PeopleController < Admin::BaseController
    before_action :set_person, only: %i[edit update show]

    def index
      @people = Person.all.paginate(page: params[:page] || 1, per_page: 10)
    end

    def new
      @person = Person.new
      @person.phones.build
    end

    def create
      @person = Person.create(person_params)

      if @person.save
        redirect_to admin_people_path, notice: 'Criado com sucesso!'
      else
        render :new
      end
    end

    def update
      if @person.update(person_params)
        redirect_to admin_people_path, notice: 'Salvo com sucesso!'
      else
        render :edit
      end
    end

    def destroy
      @person = Person.find(params[:id])
      @person.destroy
      redirect_to admin_people_path, notice: 'Removido com sucesso!'
    rescue ActiveRecord::RecordNotFound
      redirect_to admin_people_path, alert: 'Registro já foi removido'
    rescue ActiveRecord::RecordNotDestroyed
      redirect_to admin_people_path, alert: 'Não foi possível remover'
    end

    private

    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(
        :name,
        :surname,
        :document,
        :email,
        :birthdate,
        phones_attributes: %i[code number phone_type preferential]
      )
    end
  end
end

app/views/admin/people/_form.html.erb
<%= form_for [:admin, @person] do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :surname %>
      <%= f.text_field :surname, class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :document %>
      <%= f.text_field :document, class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <%= f.fields_for :phones do |phone_form| %>
      <div class="form-group col-md-6">
        <%= phone_form.label :code %>
        <%= phone_form.text_field :code, class: 'form-control' %>
      </div>
      <div class="form-group col-md-6">
        <%= phone_form.label :number %>
        <%= phone_form.text_field :number, class: 'form-control' %>
      </div>
      <div class="form-group col-md-6">
        <%= phone_form.label :phone_type %>
        <%= phone_form.text_field :phone_type, class: 'form-control' %>
      </div>
      <div class="form-check col-md-6">
        <%= phone_form.radio_button :preferential, class: 'form-check-input' %>
        <%= phone_form.label :preferential, for: 'person_phones_attributes_0_preferential_classform-check-input' %>
      </div>
    <% end %>
  </div>

  <%= f.submit t('save'), class: 'btn btn-primary' %>
  <%= link_to t('back'), :back, class: 'btn btn-secondary' %>
<% end %>

app/views/admin/people/edit.html.erb
<h2>Editar pessoa</h2>

<%= render 'form' %>

app/views/admin/people/index.html.erb
<h1 class="title">Pessoas</h1>

<div class="mb-3">
  <%= link_to 'Adicionar pessoa', new_admin_person_path, class: 'btn btn-primary' %>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">E-mail</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @people.each do |person| %>
    <tr>
      <td>
        <%= link_to person.id, edit_admin_person_path(person) %>
      </td>
      <td>
        <%= link_to person.full_name, edit_admin_person_path(person) %>
      </td>
      <td>
        <%= person.email %>
      </td>
      <td>
        <%= link_to edit_admin_person_path(person), class: 'btn btn-primary' do %>
          <i class="fa fa-eye"></i>
        <% end %>
        <%= link_to admin_person_path(person), method: :delete, class: 'btn btn-danger', data: { confirm: t(:are_you_sure)} do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="center-block">
  <%= will_paginate @people, list_classes: %w(pagination justify-content-center), previous_label: '<<', next_label: '>>' %>
</div>

app/views/admin/people/new.html.erb
<h2>Adicionar pessoa</h2>

<%= render 'form' %>