config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  namespace :admin do
    resources :rentals do
      post 'calculate-rental', to: 'rentals#calculate_rental_value', on: :new
    end
    resources :people
    resources :vehicles

    root to: 'rentals#index'
  end

  root to: 'home#index'
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= I18n.t('flashes')[key.to_sym] %>" role='alert'>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer" class="footer">
  <div class="container container-fluid">
    <div class="row">
      <div class="footer-follow col-md-6">
        <h4>Follow me</h4>
        <ul>
          <li><a href="http://br.linkedin.com/in/guihatano" target="_blank"><i class="fa fa-linkedin-square fa-3x" aria-hidden="true"></i></a></li>
          <li><a href="https://github.com/guihatano" target="_blank"><i class="fa fa-github-square fa-3x"></i></a></li>
          <li><a href="https://www.instagram.com/guihatano/" target="_blank"><i class="fa fa-instagram fa-3x"></i></a></li>
        </ul>
      </div>

      <div class="footer-menu col-md-6">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><a href="#">About</a></li>
          <li><a href="http://br.linkedin.com/in/guihatano" target="_blank">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="copyright">
    <p>Copyright <%= Date.today.year %> guiHatano Co. All Rights Reserved</p>
    <p>Code licensed under <a href="https://opensource.org/licenses/mit-license.html" target="_blank">MIT License</a></p>
  </div>
</footer>

app/views/layouts/_navbar_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">
    <%= image_tag 'logo.png', width: "78", height: "25", alt: "guihatano logo" %>
  </a>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <% if admin_signed_in? %>
          <%= link_to('Logout', destroy_admin_session_path, method: :delete) %>
        <% else %>
          <%= link_to('Login', new_admin_session_path) %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiberCareer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar_menu' %>
    <div class="container-fluid content">
      <div class="row">
        <% if admin_signed_in? %>
          <%= render 'admin/sidebar' %>
        <% end %>
        <div class="col-12 col-md-<%= admin_signed_in? ? '9 col-xl-8' : '12 col-xl-12' %> py-md-3 pl-md-5 bd-content">
          <%= render partial: 'layouts/flash_messages', locals: {flash: flash} %>
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>